#!/usr/bin/env python3
"""
Script to update the embedded PDF structure in the HTML file
Run this whenever you download new PDFs to update the embedded data
"""

import json
import os

def update_embedded_data():
    json_file = 'pdfs/downloaded-structure.json'
    js_file = 'pdfs-structure-embedded.js'
    
    if not os.path.exists(json_file):
        print(f'❌ Error: {json_file} not found')
        print('   Run the download scripts first to create the structure file')
        return False
    
    try:
        # Read the JSON file
        with open(json_file, 'r') as f:
            data = json.load(f)
        
        # Create JavaScript variable with the data
        js_content = '// Embedded PDF structure data\n'
        js_content += '// This file is auto-generated by update-embedded-data.py\n'
        js_content += '// Last updated: ' + str(os.path.getmtime(json_file)) + '\n\n'
        js_content += 'const EMBEDDED_PDF_STRUCTURE = ' + json.dumps(data, indent=2) + ';\n'
        
        # Write to JS file
        with open(js_file, 'w') as f:
            f.write(js_content)
        
        categories = list(data.keys())
        total_pdfs = sum(
            len(subtopic) 
            for cat in data.values() 
            for grade in cat.values() 
            for topic in grade.values() 
            for subtopic in topic.values()
        )
        
        print(f'✅ Successfully updated {js_file}')
        print(f'   Categories: {", ".join(categories)}')
        print(f'   Total PDFs: {total_pdfs}')
        print(f'\n   Now you can open index.html directly (file://) and it will work!')
        return True
        
    except json.JSONDecodeError as e:
        print(f'❌ Error: Invalid JSON in {json_file}')
        print(f'   {e}')
        return False
    except Exception as e:
        print(f'❌ Error: {e}')
        return False

if __name__ == '__main__':
    update_embedded_data()
